addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.10.0")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"        % "0.5.2")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.10.0")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"        % "0.14.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.5.6")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.6.4")
