addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.10.0")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"        % "0.5.2")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.10.0")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"        % "0.12.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.6.4")
